package com.hybris.tlv.usecase.gamesession.mapper

import com.hybris.tlv.database.GameSessionSchema
import com.hybris.tlv.datetime.now
import com.hybris.tlv.security.generateUuid
import com.hybris.tlv.usecase.gamesession.model.GameSession
import com.hybris.tlv.usecase.gamesession.model.GameSessionPrototype

internal fun GameSessionPrototype.toGameSession(): GameSession =
    GameSession(
        id = generateUuid(),
        utc = now(),
        assignedPoints = assignedPoints,
        yearsTraveled = 0.0,
        sensorRange = sensorRange,
        integrity = 100,
        fuel = fuel,
        materials = materials,
        cryopods = cryopods,
        currentStellarHostId = null,
        visitedStellarHosts = emptySet(),
        launchedEvents = emptySet(),
        settledPlanetId = null,
        finalHabitability = null,
        score = null,
        rocheWeight = rocheWeight,
        habitableZoneWeight = habitableZoneWeight,
        planetRadiusWeight = planetRadiusWeight,
        planetMassWeight = planetMassWeight,
        planetTelluricityWeight = planetTelluricityWeight,
        planetEccentricityWeight = planetEccentricityWeight,
        planetTemperatureWeight = planetTemperatureWeight,
        planetObliquityWeight = planetObliquityWeight,
        planetEsiWeight = planetEsiWeight,
        stellarSpectralTypeWeight = stellarSpectralTypeWeight,
        stellarMassWeight = stellarMassWeight,
        stellarAgeWeight = stellarAgeWeight,
        stellarActivityWeight = stellarActivityWeight,
        stellarRotationalPeriodWeight = stellarRotationalPeriodWeight,
        stellarGravityWeight = stellarGravityWeight,
        stellarMetallicityWeight = stellarMetallicityWeight,
        stellarEffectiveTemperatureWeight = stellarEffectiveTemperatureWeight,
        planetProtectionWeight = planetProtectionWeight,
        planetTidalLockingWeight = planetTidalLockingWeight,
        planetMassLowerLimit = planetMassLowerLimit,
        planetMassIdealUpperLimit = planetMassIdealUpperLimit,
        planetMassMaxUpperLimit = planetMassMaxUpperLimit,
        planetRadiusLowerLimit = planetRadiusLowerLimit,
        planetRadiusIdealUpperLimit = planetRadiusIdealUpperLimit,
        planetRadiusMaxUpperLimit = planetRadiusMaxUpperLimit,
        stellarHostEffectiveTemperatureMaxDeviation = stellarHostEffectiveTemperatureMaxDeviation
    )

internal fun GameSession.toGameSessionSchema(): GameSessionSchema =
    GameSessionSchema(
        id = id,
        utc = utc,
        assignedPoints = assignedPoints,
        yearsTraveled = yearsTraveled,
        sensorRange = sensorRange,
        integrity = integrity,
        fuel = fuel,
        materials = materials,
        cryopods = cryopods,
        currentStellarHostId = currentStellarHostId,
        visitedStellarHosts = visitedStellarHosts,
        launchedEvents = launchedEvents,
        settledPlanetId = settledPlanetId,
        finalHabitability = finalHabitability,
        score = score,
        rocheWeight = rocheWeight,
        habitableZoneWeight = habitableZoneWeight,
        planetRadiusWeight = planetRadiusWeight,
        planetMassWeight = planetMassWeight,
        planetTelluricityWeight = planetTelluricityWeight,
        planetEccentricityWeight = planetEccentricityWeight,
        planetTemperatureWeight = planetTemperatureWeight,
        planetObliquityWeight = planetObliquityWeight,
        planetEsiWeight = planetEsiWeight,
        stellarSpectralTypeWeight = stellarSpectralTypeWeight,
        stellarMassWeight = stellarMassWeight,
        stellarAgeWeight = stellarAgeWeight,
        stellarActivityWeight = stellarActivityWeight,
        stellarRotationalPeriodWeight = stellarRotationalPeriodWeight,
        stellarGravityWeight = stellarGravityWeight,
        stellarMetallicityWeight = stellarMetallicityWeight,
        stellarEffectiveTemperatureWeight = stellarEffectiveTemperatureWeight,
        planetProtectionWeight = planetProtectionWeight,
        planetTidalLockingWeight = planetTidalLockingWeight,
        planetMassLowerLimit = planetMassLowerLimit,
        planetMassIdealUpperLimit = planetMassIdealUpperLimit,
        planetMassMaxUpperLimit = planetMassMaxUpperLimit,
        planetRadiusLowerLimit = planetRadiusLowerLimit,
        planetRadiusIdealUpperLimit = planetRadiusIdealUpperLimit,
        planetRadiusMaxUpperLimit = planetRadiusMaxUpperLimit,
        stellarHostEffectiveTemperatureMaxDeviation = stellarHostEffectiveTemperatureMaxDeviation
    )

internal fun GameSessionSchema.toGameSession(): GameSession =
    GameSession(
        id = id,
        utc = utc,
        assignedPoints = assignedPoints,
        yearsTraveled = yearsTraveled,
        sensorRange = sensorRange,
        integrity = integrity,
        fuel = fuel,
        materials = materials,
        cryopods = cryopods,
        currentStellarHostId = currentStellarHostId,
        visitedStellarHosts = visitedStellarHosts,
        launchedEvents = launchedEvents,
        settledPlanetId = settledPlanetId,
        finalHabitability = finalHabitability,
        score = score,
        rocheWeight = rocheWeight,
        habitableZoneWeight = habitableZoneWeight,
        planetRadiusWeight = planetRadiusWeight,
        planetMassWeight = planetMassWeight,
        planetTelluricityWeight = planetTelluricityWeight,
        planetEccentricityWeight = planetEccentricityWeight,
        planetTemperatureWeight = planetTemperatureWeight,
        planetObliquityWeight = planetObliquityWeight,
        planetEsiWeight = planetEsiWeight,
        stellarSpectralTypeWeight = stellarSpectralTypeWeight,
        stellarMassWeight = stellarMassWeight,
        stellarAgeWeight = stellarAgeWeight,
        stellarActivityWeight = stellarActivityWeight,
        stellarRotationalPeriodWeight = stellarRotationalPeriodWeight,
        stellarGravityWeight = stellarGravityWeight,
        stellarMetallicityWeight = stellarMetallicityWeight,
        stellarEffectiveTemperatureWeight = stellarEffectiveTemperatureWeight,
        planetProtectionWeight = planetProtectionWeight,
        planetTidalLockingWeight = planetTidalLockingWeight,
        planetMassLowerLimit = planetMassLowerLimit,
        planetMassIdealUpperLimit = planetMassIdealUpperLimit,
        planetMassMaxUpperLimit = planetMassMaxUpperLimit,
        planetRadiusLowerLimit = planetRadiusLowerLimit,
        planetRadiusIdealUpperLimit = planetRadiusIdealUpperLimit,
        planetRadiusMaxUpperLimit = planetRadiusMaxUpperLimit,
        stellarHostEffectiveTemperatureMaxDeviation = stellarHostEffectiveTemperatureMaxDeviation
    )
