#Gradle
org.gradle.jvmargs=-Xmx8192M -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.jvm.modularity.inferModulePath=true
org.gradle.daemon=true
#Kotlin
kotlin.code.style=official
kotlin.mpp.applyDefaultHierarchyTemplate=false
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
#Compose
compose.desktop.packaging.checkJdkVendor=false
