[versions]

kover = "0.9.4"
kotlin = "2.3.0"
kotlinx-serialization = "1.9.0"
kotlinx-datetime = "0.7.1"
kotlinx-coroutines = "1.10.2"
kotlin-ktor = "3.3.3"
compose-multiplatform = "1.9.3"
lifecycle = "2.9.6"
navigation = "2.9.1"
sqldelight = "2.2.1"
sqldelight-jdbc = "3.51.1.0"
coil = "3.3.0"
android-plugin = "8.13.2"
android-startup = "1.2.0"
androidx-exoplayer = "1.9.0"
android-test = "1.10.0"
logging = "2.0.17"
sentry = "0.21.0"
javafx = "21.0.9"

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
androidApplication = { id = "com.android.application", version.ref = "android-plugin" }
androidLibrary = { id = "com.android.library", version.ref = "android-plugin" }
sentry = { id = "io.sentry.kotlin.multiplatform.gradle", version.ref = "sentry" }

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlin-ktor = { group = "io.ktor", name = "ktor-client-core", version.ref = "kotlin-ktor" }
kotlin-ktor-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "kotlin-ktor" }
kotlin-ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "kotlin-ktor" }
kotlin-ktor-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "kotlin-ktor" }
kotlin-ktor-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "kotlin-ktor" }
kotlin-ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "kotlin-ktor" }
kotlin-ktor-content = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "kotlin-ktor" }
kotlin-ktor-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "kotlin-ktor" }
kotlin-ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "kotlin-ktor" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
sqldelight-runtime = { group = "app.cash.sqldelight", name = "runtime", version.ref = "sqldelight" }
sqldelight-primitives = { group = "app.cash.sqldelight", name = "primitive-adapters", version.ref = "sqldelight" }
sqldelight-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-native = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqldelight" }
sqldelight-jvm = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
sqldelight-jdbc = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqldelight-jdbc" }
compose-backhandler = { group = "org.jetbrains.compose.ui", name = "ui-backhandler", version.ref = "compose-multiplatform" }
lifecycle = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "android-startup" }
androidx-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidx-exoplayer" }
androidx-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "android-test" }
logging = { group = "org.slf4j", name = "slf4j-simple", version.ref = "logging" }
javafx-base = { group = "org.openjfx", name = "javafx-base", version.ref = "javafx" }
javafx-graphics = { group = "org.openjfx", name = "javafx-graphics", version.ref = "javafx" }
javafx-media = { group = "org.openjfx", name = "javafx-media", version.ref = "javafx" }
javafx-swing = { group = "org.openjfx", name = "javafx-swing", version.ref = "javafx" }

[bundles]
common = [
    "kotlin-ktor",
    "kotlin-ktor-mock",
    "kotlin-ktor-content",
    "kotlin-ktor-serialization",
    "kotlin-ktor-encoding",
    "kotlin-ktor-logging",
    "sqldelight-runtime",
    "sqldelight-primitives",
    "sqldelight-coroutines",
    "kotlinx-serialization",
    "kotlinx-datetime",
    "compose-backhandler",
    "lifecycle",
    "lifecycle-runtime",
    "navigation",
    "coil-compose"
]
common-test = [
    "kotlin-test",
]
android = [
    "kotlin-ktor-okhttp",
    "sqldelight-android",
    "sqldelight-jvm",
    "androidx-startup",
    "androidx-exoplayer",
]
ios = [
    "kotlin-ktor-darwin",
    "sqldelight-native",
]
desktop = [
    "kotlin-ktor-cio",
    "sqldelight-jvm",
    "sqldelight-jdbc",
    "kotlinx-coroutines-swing",
    "logging",
]
