[versions]

# Kotlin
kover = "0.9.4"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
kotlinx-datetime = "0.7.1"

# Ktor
ktor = "3.4.0"

# SQLDelight
sqldelight = "2.2.1"
sqldelight-jdbc = "3.51.1.0"

# UI & Lifecycle
compose-multiplatform = "1.10.0"
compose-material3 = "1.9.0"
compose-icons = "1.7.3"
lifecycle = "2.9.6"
navigation = "2.9.1"
coil = "3.3.0"

# Android
android-plugin = "8.13.2"
android-startup = "1.2.0"
androidx-exoplayer = "1.9.1"
android-test = "1.10.2"

# Desktop
logging = "2.0.17"
javafx = "21.0.9"

# Web
sql-js = "1.6.2"
webpack = "9.1.0"

# Crashlytics
sentry = "0.21.0"

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
sentry = { id = "io.sentry.kotlin.multiplatform.gradle", version.ref = "sentry" }

[libraries]
# Kotlin
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Ktor
ktor = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor"}
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-content = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# SQLDelight
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-primitives = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-worker = { module = "app.cash.sqldelight:web-worker-driver", version.ref = "sqldelight" }
sqldelight-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqldelight-jdbc" }

# UI
compose-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose-multiplatform" }
compose-test-junit = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "compose-multiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-icons" }
lifecycle = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }

# Android
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "android-startup" }
androidx-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-exoplayer" }
androidx-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "android-test" }

# Desktop
logging = { module = "org.slf4j:slf4j-simple", version.ref = "logging" }
javafx-base = { module = "org.openjfx:javafx-base", version.ref = "javafx" }
javafx-graphics = { module = "org.openjfx:javafx-graphics", version.ref = "javafx" }
javafx-media = { module = "org.openjfx:javafx-media", version.ref = "javafx" }
javafx-swing = { module = "org.openjfx:javafx-swing", version.ref = "javafx" }

# Web
sql-worker = { module = "npm:@cashapp/sqldelight-sqljs-worker", version.ref = "sqldelight" }
sql-js = { module = "npm:sql.js", version.ref = "sql-js" }
webpack = { module = "npm:copy-webpack-plugin", version.ref = "webpack" }

[bundles]
common = [
    "kotlinx-coroutines-core",
    "kotlinx-serialization",
    "kotlinx-datetime",
    "ktor",
    "ktor-mock",
    "ktor-logging",
    "ktor-content",
    "ktor-encoding",
    "ktor-serialization",
    "sqldelight-runtime",
    "sqldelight-primitives",
    "sqldelight-coroutines",
    "compose-runtime",
    "compose-foundation",
    "compose-backhandler",
    "compose-ui",
    "compose-resources",
    "compose-preview",
    "compose-material3",
    "compose-icons",
    "lifecycle",
    "lifecycle-runtime",
    "navigation",
    "coil-compose"
]
common-test = [
    "kotlin-test",
    "kotlinx-coroutines-test",
    "compose-test",
]
android = [
    "ktor-okhttp",
    "sqldelight-android",
    "androidx-startup",
    "androidx-exoplayer",
]
ios = [
    "ktor-darwin",
    "sqldelight-native",
]
desktop = [
    "ktor-java",
    "sqldelight-jvm",
    "sqldelight-jdbc",
    "kotlinx-coroutines-swing",
    "logging",
]
web = [
    "ktor-js",
    "sqldelight-worker"
]
