package com.hybris.tlv.ui.screen.newgame

internal const val NEW_GAME_SCREEN = "new_game_screen"
internal const val NEW_GAME_SCREEN_NEW_GAME_CONTENT = "new_game_screen_new_game_content"
internal const val NEW_GAME_SCREEN_NEW_GAME_CONTENT_POINTS_TEXT = "new_game_screen_new_game_content_points_text"
internal const val NEW_GAME_SCREEN_NEW_GAME_CONTENT_POINTS = "new_game_screen_new_game_content_points"
internal const val NEW_GAME_SCREEN_NEW_GAME_CONTENT_ENGINE = "new_game_screen_new_game_content_engine"
internal const val NEW_GAME_SCREEN_START_CONTENT = "new_game_screen_start_content"
internal const val NEW_GAME_SCREEN_START_CONTENT_CATASTROPHE = "new_game_screen_start_content_catastrophe"
internal const val NEW_GAME_SCREEN_START_CONTENT_CATASTROPHE_DESCRIPTION = "new_game_screen_start_content_catastrophe_description"
