package com.hybris.tlv.ui.screen.mainmenu

internal const val MAIN_MENU_SCREEN = "main_menu_screen"
internal const val MAIN_MENU_SCREEN_BOTTOM_BAR = "main_menu_screen_bottom_bar"
internal const val MAIN_MENU_SCREEN_MAIN_MENU_CONTENT = "main_menu_screen_main_menu_content"
internal const val MAIN_MENU_SCREEN_MAIN_MENU_CONTENT_NEW_GAME = "main_menu_screen_main_menu_content_new_game"
internal const val MAIN_MENU_SCREEN_MAIN_MENU_CONTENT_CONTINUE = "main_menu_screen_main_menu_content_continue"
internal const val MAIN_MENU_SCREEN_MAIN_CONTENT_STELLAR_EXPLORER = "main_menu_screen_main_content_stellar_explorer"
internal const val MAIN_MENU_SCREEN_MAIN_MENU_CONTENT_LEARN = "main_menu_screen_main_menu_content_learn"
internal const val MAIN_MENU_SCREEN_MAIN_MENU_CONTENT_SCORES = "main_menu_screen_main_menu_content_scores"
internal const val MAIN_MENU_SCREEN_MAIN_MENU_CONTENT_ACHIEVEMENTS = "main_menu_screen_main_menu_content_achievements"
