package com.hybris.tlv.ui.screen.game

internal const val GAME_SCREEN = "game_screen"
internal const val GAME_SCREEN_STATUS_BAR = "game_screen_status_bar"
internal const val GAME_SCREEN_NAVIGATION_BAR = "game_screen_navigation_bar"
internal const val GAME_SCREEN_NAVIGATION_BAR_ITEM_SHIP = "game_screen_navigation_bar_item_ship"
internal const val GAME_SCREEN_NAVIGATION_BAR_ITEM_SYSTEM = "game_screen_navigation_bar_item_system"
internal const val GAME_SCREEN_NAVIGATION_BAR_ITEM_TRAVEL = "game_screen_navigation_bar_item_travel"
internal const val GAME_SCREEN_PROGRESS_INDICATOR = "game_screen_progress_indicator"
internal const val GAME_SCREEN_SHIP_CONTENT = "game_screen_ship_content"
internal const val GAME_SCREEN_SHIP_CONTENT_YEARS_TRAVELED = "game_screen_ship_content_years_traveled"
internal const val GAME_SCREEN_SHIP_CONTENT_SENSOR = "game_screen_ship_content_sensor"
internal const val GAME_SCREEN_SHIP_CONTENT_SPEED = "game_screen_ship_content_speed"
internal const val GAME_SCREEN_SHIP_CONTENT_INTEGRITY = "game_screen_ship_content_integrity"
internal const val GAME_SCREEN_SHIP_CONTENT_FUEL = "game_screen_ship_content_fuel"
internal const val GAME_SCREEN_SHIP_CONTENT_MATERIALS = "game_screen_ship_content_materials"
internal const val GAME_SCREEN_SHIP_CONTENT_CRYOPODS = "game_screen_ship_content_cryopods"
internal const val GAME_SCREEN_SYSTEM_CONTENT = "game_screen_system_content"
internal const val GAME_SCREEN_SYSTEM_CONTENT_STELLAR_HOST = "game_screen_system_content_stellar_host"
internal const val GAME_SCREEN_SYSTEM_CONTENT_PLANET = "game_screen_system_content_planet"
internal const val GAME_SCREEN_TRAVEL_CONTENT = "game_screen_travel_content"
internal const val GAME_SCREEN_TRAVEL_CONTENT_STELLAR_HOST = "game_screen_travel_content_stellar_host"
