package com.hybris.tlv.usecase.gamesession.model

internal enum class GameOver {
    // Ship is destroyed
    INTEGRITY_ZERO,
    INTEGRITY_ZERO_YEARS_FEW,
    INTEGRITY_ZERO_YEARS_SOME,
    INTEGRITY_ZERO_YEARS_LOTS,
    INTEGRITY_ZERO_MATERIALS_ZERO,
    INTEGRITY_ZERO_MATERIALS_LOW,
    INTEGRITY_ZERO_MATERIALS_ENOUGH,
    INTEGRITY_ZERO_CRYOPODS_ZERO,
    INTEGRITY_ZERO_CRYOPODS_ONE,
    INTEGRITY_ZERO_CRYOPODS_LOW,
    INTEGRITY_ZERO_CRYOPODS_ENOUGH,
    INTEGRITY_ZERO_FUEL_LOW,
    INTEGRITY_ZERO_FUEL_SOME,
    INTEGRITY_ZERO_FUEL_PLENTY,
    INTEGRITY_ZERO_YEARS_LOTS_CRYOPODS_BUSTLING,

    // Ship ran out of fuel
    FUEL_ZERO,
    FUEL_ZERO_YEARS_FEW,
    FUEL_ZERO_YEARS_SOME,
    FUEL_ZERO_YEARS_LOTS,
    FUEL_ZERO_MATERIALS_ZERO,
    FUEL_ZERO_MATERIALS_LOW,
    FUEL_ZERO_MATERIALS_ENOUGH,
    FUEL_ZERO_CRYOPODS_ZERO,
    FUEL_ZERO_CRYOPODS_ONE,
    FUEL_ZERO_CRYOPODS_NEAR_ZERO,
    FUEL_ZERO_CRYOPODS_TOO_LOW,
    FUEL_ZERO_CRYOPODS_LOW,
    FUEL_ZERO_CRYOPODS_ENOUGH,
    FUEL_ZERO_INTEGRITY_LOW,
    FUEL_ZERO_INTEGRITY_ENOUGH,
    FUEL_ZERO_INTEGRITY_PRISTINE,
    FUEL_ZERO_MATERIALS_PLENTY_CRYOPODS_BUSTLING,
    FUEL_ZERO_INTEGRITY_ENOUGH_MATERIALS_ENOUGH_CRYOPODS_BUSTLING,

    // Solar System Planets
    MERCURY,
    VENUS,
    EARTH,
    MARS,
    JUPITER,
    SATURN,
    URANUS,
    NEPTUNE,

    // Habitability: Deadly
    HABITABILITY_DEADLY,
    HABITABILITY_DEADLY_CRYOPODS_ENOUGH,
    HABITABILITY_DEADLY_INTEGRITY_LOW,
    HABITABILITY_DEADLY_INTEGRITY_MID_LOW_MATERIALS_ENOUGH,

    // Habitability: Very Low
    HABITABILITY_VERY_LOW,
    HABITABILITY_VERY_LOW_CRYOPODS_ENOUGH_MATERIALS_ENOUGH,
    HABITABILITY_VERY_LOW_CRYOPODS_MID_MATERIALS_ENOUGH,
    HABITABILITY_VERY_LOW_INTEGRITY_LOW,

    // Habitability: Low
    HABITABILITY_LOW,
    HABITABILITY_LOW_MATERIALS_ENOUGH_CRYOPODS_ENOUGH,
    HABITABILITY_LOW_MATERIALS_ENOUGH_CRYOPODS_ENOUGH_INTEGRITY_PRISTINE,
    HABITABILITY_LOW_MATERIALS_ENOUGH_CRYOPODS_ENOUGH_FUEL_PLENTY,
    HABITABILITY_LOW_MATERIALS_ENOUGH_CRYOPODS_LOW,
    HABITABILITY_LOW_MATERIALS_ENOUGH_CRYOPODS_ZERO,
    HABITABILITY_LOW_MATERIALS_LOW_CRYOPODS_ENOUGH,
    HABITABILITY_LOW_MATERIALS_LOW_CRYOPODS_LOW,
    HABITABILITY_LOW_MATERIALS_LOW_CRYOPODS_ZERO,

    // Habitability: Medium
    HABITABILITY_MEDIUM,
    HABITABILITY_MEDIUM_MATERIALS_ENOUGH_CRYOPODS_ENOUGH,
    HABITABILITY_MEDIUM_MATERIALS_ENOUGH_CRYOPODS_ENOUGH_YEARS_LOTS,
    HABITABILITY_MEDIUM_MATERIALS_ENOUGH_CRYOPODS_BUSTLING,
    HABITABILITY_MEDIUM_MATERIALS_ENOUGH_CRYOPODS_LOW,
    HABITABILITY_MEDIUM_MATERIALS_ENOUGH_CRYOPODS_ZERO,
    HABITABILITY_MEDIUM_MATERIALS_LOW_CRYOPODS_ENOUGH_INTEGRITY_ENOUGH,
    HABITABILITY_MEDIUM_MATERIALS_LOW_CRYOPODS_ENOUGH,
    HABITABILITY_MEDIUM_MATERIALS_LOW_CRYOPODS_LOW,
    HABITABILITY_MEDIUM_MATERIALS_LOW_CRYOPODS_ZERO,

    // Habitability: High
    HABITABILITY_HIGH,
    HABITABILITY_HIGH_MATERIALS_ENOUGH_CRYOPODS_ENOUGH,
    HABITABILITY_HIGH_MATERIALS_ENOUGH_CRYOPODS_ENOUGH_YEARS_LOTS,
    HABITABILITY_HIGH_MATERIALS_ENOUGH_CRYOPODS_BUSTLING,
    HABITABILITY_HIGH_MATERIALS_ENOUGH_CRYOPODS_LOW,
    HABITABILITY_HIGH_MATERIALS_ENOUGH_CRYOPODS_ZERO,
    HABITABILITY_HIGH_MATERIALS_LOW_CRYOPODS_ENOUGH_INTEGRITY_ENOUGH,
    HABITABILITY_HIGH_MATERIALS_LOW_CRYOPODS_ENOUGH,
    HABITABILITY_HIGH_MATERIALS_LOW_CRYOPODS_LOW,
    HABITABILITY_HIGH_MATERIALS_LOW_CRYOPODS_ZERO,

    // Default
    GAME_OVER
}
