package com.hybris.tlv.usecase.gamesession.model

internal data class GameSession(
    val id: String,
    val utc: String,
    val assignedPoints: Int,
    val yearsTraveled: Double,
    val sensorRange: Int,
    val integrity: Int,
    val fuel: Int,
    val materials: Int,
    val cryopods: Int,
    val currentStellarHostId: String?,
    val visitedStellarHosts: Set<String>,
    val launchedEvents: Set<String>,
    val settledPlanetId: String?,
    val finalHabitability: Double?,
    val score: Double?,
    val rocheWeight: Double,
    val habitableZoneWeight: Double,
    val planetRadiusWeight: Double,
    val planetMassWeight: Double,
    val planetTelluricityWeight: Double,
    val planetEccentricityWeight: Double,
    val planetTemperatureWeight: Double,
    val planetObliquityWeight: Double,
    val planetEsiWeight: Double,
    val stellarSpectralTypeWeight: Double,
    val stellarMassWeight: Double,
    val stellarAgeWeight: Double,
    val stellarActivityWeight: Double,
    val stellarRotationalPeriodWeight: Double,
    val stellarGravityWeight: Double,
    val stellarMetallicityWeight: Double,
    val stellarEffectiveTemperatureWeight: Double,
    val planetProtectionWeight: Double,
    val planetTidalLockingWeight: Double,
    val planetMassLowerLimit: Double,
    val planetMassIdealUpperLimit: Double,
    val planetMassMaxUpperLimit: Double,
    val planetRadiusLowerLimit: Double,
    val planetRadiusIdealUpperLimit: Double,
    val planetRadiusMaxUpperLimit: Double,
    val stellarHostEffectiveTemperatureMaxDeviation: Double
)
